version: '3.9'

services:
  postgres: 
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 24466666
      POSTGRES_DB: my_project_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://user:244466666@postgres:5432/dbc
    ports: 
    - '9999:9999'
    volumes:
      - .:/api
    depends_on:
      - postgres

volumes:
  api:
  postgres_data:

