version: '3.9'

services:
  postgres: 
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 244466666
      POSTGRES_DB: dbc
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schemas.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - senai

  webhook:
    build: .
    ports: 
      - '9999:9999'
    networks:
      - senai
    depends_on:
      - rabbitmq
    volumes:
      - ./secrets/private_key.pem:/api/secrets/private_key.pem:ro
    environment:
      PRIVATE_KEY_PATH: ./secrets/private_key.pem   

  storage:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:244466666@postgres:5432/dbc 
    ports:
      - '9998:9998'
    networks:
      - senai
    depends_on:
      - postgres
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - senai

networks:
  senai:
    driver: bridge

volumes:
  postgres_data: