version: '3.9'

services:
  postgres: 
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 244466666
      POSTGRES_DB: dbc
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - senai

  webhook:
    build: .
    ports: 
    - '9999:9999'
    networks:
      - senai

  storage:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:244466666@postgres:5432/dbc 
    ports:
      - '9998:9998'
    networks:
      - senai

networks:
  senai:
    driver: bridge

volumes:
  postgres_data:

