version: '3.9'

services:
  postgres: 
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 244466666
      POSTGRES_DB: dbc
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - senai

  webhook:
    build: .
    ports: 
      - '9999:9999'
    networks:
      - senai

  storage:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:244466666@postgres:5432/dbc 
    ports:
      - '9998:9998'
    networks:
      - senai

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - senai

networks:
  senai:
    driver: bridge

volumes:
  postgres_data: